export default {
  USER_LOGGING_IN: 'USER_LOGGING_IN',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',

  DATA: {
    GET_HEADER: 'GET_HEADER',
    GET_HOME: 'GET_HOME',
    GET_COLLECTION: 'GET_COLLECTION',
    GET_PRODUCT: 'GET_PRODUCT',
    GET_ALL: 'GET_ALL',
    GET_PAGE: 'GET_PAGE',
    GET_BLOG: 'GET_BLOG',
    GET_ARTICLE: 'GET_ARTICLE',
    GET_SEARCH: 'GET_SEARCH',
  },
  PRODUCT: {
    CHANGE_FEATURED_IMAGE: 'CHANGE_FEATURED_IMAGE',
    CHANGE_QUANTITY: 'CHANGE_QUANTITY',
    CHANGE_VARIANT: 'CHANGE_VARIANT',
    ADD_TO_CART: 'ADD_TO_CART',
  },
  CART: {
    SET_CART: 'SET_CART',
    TOGGLE: 'TOGGLE',
    REMOVE_ITEM: 'REMOVE_ITEM',
    INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
    DECREMENT_QUANTITY: 'DECREMENT_QUANTITY',
  },
  ERRORS: {
    ERROR: 'ERROR',
    RESET_ERROR: 'RESET_ERROR',
  },
}